@echo off
rem AgentZero launcher for Windows: runs this workspace's own runtime (src\) with a
rem Python that has PyYAML. Usage: a0 memory|knowledge|skills <command> [args...]
rem Without it the same command is: set PYTHONPATH=src && python -m <package> ...
rem Generated by the framework; do not edit - see SETTLED #71.
setlocal
cd /d "%~dp0"
set "PYTHONPATH=%~dp0src;%PYTHONPATH%"
if "%~1"=="" goto usage
if /i "%~1"=="memory" goto run
if /i "%~1"=="knowledge" goto run
if /i "%~1"=="skills" goto run
:usage
echo usage: a0 memory^|knowledge^|skills ^<command^> [args...] 1>&2
exit /b 2
:run
if defined AGENTZERO_PYTHON (
  "%AGENTZERO_PYTHON%" -c "import yaml" >nul 2>&1 && ( "%AGENTZERO_PYTHON%" -m %* & exit /b )
)
for %%P in (python py python3) do (
  %%P -c "import sys, yaml; sys.exit(sys.version_info < (3, 11))" >nul 2>&1 && ( %%P -m %* & exit /b )
)
python -m %*
