"""Memory: Facts, Timeline, Archive, and graph index (ADR 0005 / 0006)."""

# Before anything imports yaml: a Python without PyYAML gets a fix, not a traceback.
from memory.host import require_yaml

require_yaml()

from memory.graph import (
    GraphActivation,
    GraphEdge,
    GraphEntity,
    GraphIndexLine,
    MemoryGraph,
    activate_graph,
    confirm_graph_item,
    export_graph_markdown,
    parse_graph,
    query_graph,
    record_edge,
    record_entity,
    retire_graph_item,
)
from memory.lifecycle import (
    AsOfSelection,
    Episode,
    HotSet,
    MemoryEntry,
    TimelineQuery,
    archive_move,
    confirm_entry,
    confirm_episode,
    load_hot_set,
    load_set,
    parse_entry,
    parse_episode,
    propose_fact_from_episode,
    query_facts,
    query_timeline,
    record_entry,
    record_episode,
    remember_fact,
    retire_entry,
    retire_episode,
    select_facts_as_of,
    winning_entry,
)
from memory.taskclass import ScoredRun, TaskClass, derive, detect, scored_runs_by_class

__all__ = [
    "AsOfSelection",
    "Episode",
    "GraphActivation",
    "GraphEdge",
    "GraphEntity",
    "GraphIndexLine",
    "HotSet",
    "MemoryEntry",
    "MemoryGraph",
    "ScoredRun",
    "TaskClass",
    "TimelineQuery",
    "activate_graph",
    "archive_move",
    "confirm_entry",
    "confirm_episode",
    "confirm_graph_item",
    "derive",
    "detect",
    "export_graph_markdown",
    "load_hot_set",
    "load_set",
    "parse_entry",
    "parse_episode",
    "parse_graph",
    "propose_fact_from_episode",
    "query_facts",
    "query_graph",
    "query_timeline",
    "record_edge",
    "record_entity",
    "record_entry",
    "record_episode",
    "remember_fact",
    "retire_entry",
    "retire_episode",
    "retire_graph_item",
    "scored_runs_by_class",
    "select_facts_as_of",
    "winning_entry",
]
